"""flexible assignments, scorecard templates, review case_number

Revision ID: 5fbd1f2d790c
Revises: caee5fac1c97
Create Date: 2026-08-22 02:40:50.236324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbd1f2d790c'
down_revision: Union[str, Sequence[str], None] = 'caee5fac1c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('case_type', sa.Enum('Initial Fix', 'Scheduled Fix', 'Service Request', 'Security Fix', 'Incident Fix', 'No Cases', name='casetypeenum', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecard_templates_case_type'), 'scorecard_templates', ['case_type'], unique=False)
    op.create_table('scorecard_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('error_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('penalty_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'error_name', name='uq_scorecard_items_template_error')
    )
    op.create_index(op.f('ix_scorecard_items_template_id'), 'scorecard_items', ['template_id'], unique=False)
    op.drop_constraint(op.f('ck_qa_assignments_exactly_one_target'), 'qa_assignments', type_='check')
    op.create_check_constraint('ck_qa_assignments_at_least_one_target', 'qa_assignments', 'num_nonnulls(support_agent_id, specialized_case_type) >= 1')
    op.add_column('reviews', sa.Column('case_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'case_number')
    op.drop_constraint('ck_qa_assignments_at_least_one_target', 'qa_assignments', type_='check')
    op.create_check_constraint(op.f('ck_qa_assignments_exactly_one_target'), 'qa_assignments', 'num_nonnulls(support_agent_id, specialized_case_type) = 1')
    op.drop_index(op.f('ix_scorecard_items_template_id'), table_name='scorecard_items')
    op.drop_table('scorecard_items')
    op.drop_index(op.f('ix_scorecard_templates_case_type'), table_name='scorecard_templates')
    op.drop_table('scorecard_templates')
    # ### end Alembic commands ###
