"""bad feedback tables

Revision ID: 615b6b3d8d0c
Revises: 67cc89d92210
Create Date: 2026-08-28 20:48:57.416608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '615b6b3d8d0c'
down_revision: Union[str, Sequence[str], None] = '67cc89d92210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('customer_info', sa.Text(), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('related_case', sa.String(length=255), nullable=True),
    sa.Column('qa_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='reviewstatusenum', native_enum=False, length=20), server_default='pending', nullable=False),
    sa.Column('assigned_qa_id', sa.Integer(), nullable=True),
    sa.Column('qa_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_qa_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qa_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bad_feedbacks_assigned_qa_id'), 'bad_feedbacks', ['assigned_qa_id'], unique=False)
    op.create_index(op.f('ix_bad_feedbacks_created_at'), 'bad_feedbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_bad_feedbacks_fb_date'), 'bad_feedbacks', ['fb_date'], unique=False)
    op.create_index(op.f('ix_bad_feedbacks_qa_id'), 'bad_feedbacks', ['qa_id'], unique=False)
    op.create_table('bad_feedback_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('Support', 'Sales', name='agentkindenum', native_enum=False, length=20), nullable=False),
    sa.Column('fault', sa.Enum('Full Fault', 'Partial Fault', 'Warning', 'No Fault', name='faultenum', native_enum=False, length=20), nullable=True),
    sa.Column('qa_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['bad_feedbacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bad_feedback_agents_feedback_id'), 'bad_feedback_agents', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_bad_feedback_agents_user_id'), 'bad_feedback_agents', ['user_id'], unique=False)
    # NOTE: autogenerate also flagged pre-existing drift on
    # qa_assignments (ended_at column, unique index) that predates this
    # change — deliberately NOT touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_bad_feedback_agents_user_id'), table_name='bad_feedback_agents')
    op.drop_index(op.f('ix_bad_feedback_agents_feedback_id'), table_name='bad_feedback_agents')
    op.drop_table('bad_feedback_agents')
    op.drop_index(op.f('ix_bad_feedbacks_qa_id'), table_name='bad_feedbacks')
    op.drop_index(op.f('ix_bad_feedbacks_fb_date'), table_name='bad_feedbacks')
    op.drop_index(op.f('ix_bad_feedbacks_created_at'), table_name='bad_feedbacks')
    op.drop_index(op.f('ix_bad_feedbacks_assigned_qa_id'), table_name='bad_feedbacks')
    op.drop_table('bad_feedbacks')
    # ### end Alembic commands ###
