"""initial schema

Revision ID: 8b339dd2d0a8
Revises: 
Create Date: 2026-08-24 20:07:46.185522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b339dd2d0a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('case_type', sa.Enum('Initial Fix', 'Scheduled Fix', 'Service Request', 'Security Fix', 'Incident Fix', 'No Cases', name='casetypeenum', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecard_templates_case_type'), 'scorecard_templates', ['case_type'], unique=False)
    op.create_table('system_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_prompts_key'), 'system_prompts', ['key'], unique=False)
    op.create_index('uq_system_prompts_key_active', 'system_prompts', ['key'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('qa_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qa_id', sa.Integer(), nullable=False),
    sa.Column('support_agent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qa_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_assignments_qa_id'), 'qa_assignments', ['qa_id'], unique=False)
    op.create_index(op.f('ix_qa_assignments_support_agent_id'), 'qa_assignments', ['support_agent_id'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_agent_id', sa.Integer(), nullable=False),
    sa.Column('qa_id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.Enum('Initial Fix', 'Scheduled Fix', 'Service Request', 'Security Fix', 'Incident Fix', 'No Cases', name='casetypeenum', native_enum=False, length=50), nullable=False),
    sa.Column('case_number', sa.String(length=255), nullable=True),
    sa.Column('scorecard_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='reviewstatusenum', native_enum=False, length=20), server_default='completed', nullable=False),
    sa.Column('assigned_qa_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_qa_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qa_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_assigned_qa_id'), 'reviews', ['assigned_qa_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_qa_id'), 'reviews', ['qa_id'], unique=False)
    op.create_index(op.f('ix_reviews_support_agent_id'), 'reviews', ['support_agent_id'], unique=False)
    op.create_table('scorecard_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('error_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=200), server_default=sa.text("'General'"), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('penalty_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['scorecard_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'error_name', name='uq_scorecard_items_template_error')
    )
    op.create_index(op.f('ix_scorecard_items_template_id'), 'scorecard_items', ['template_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Supervisor', 'QA', 'Support', name='roleenum', native_enum=False, length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_scorecard_items_template_id'), table_name='scorecard_items')
    op.drop_table('scorecard_items')
    op.drop_index(op.f('ix_reviews_support_agent_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_qa_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_assigned_qa_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_qa_assignments_support_agent_id'), table_name='qa_assignments')
    op.drop_index(op.f('ix_qa_assignments_qa_id'), table_name='qa_assignments')
    op.drop_table('qa_assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_system_prompts_key_active', table_name='system_prompts', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_system_prompts_key'), table_name='system_prompts')
    op.drop_table('system_prompts')
    op.drop_index(op.f('ix_scorecard_templates_case_type'), table_name='scorecard_templates')
    op.drop_table('scorecard_templates')
    # ### end Alembic commands ###
